import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { createTheme, DirectionProvider, MantineProvider } from "@mantine/core";
import "vazirmatn/Vazirmatn-font-face.css"
import '@mantine/core/styles.css';
import "./globals.css";

const theme = createTheme({});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
        <html lang="fa" dir="rtl">
            <body className={`${geistSans.variable} ${geistMono.variable}`}>
                <DirectionProvider initialDirection="rtl">
                    <MantineProvider theme={theme}>
                        {children}
                    </MantineProvider>
                </DirectionProvider>
            </body>
        </html>
  );
}
